### ISSUE TITLE
Note swipe actions

### ISSUE THREAD

**Issue by spiral6** [redsolver/notable-mobile#13]
Removal of the note swipe actions is not ideal, because they can be intuitive and useful for the user's preference, even if the functionality is redundant. 

My proposal is that swiping left on a note pulls up the delete button like before, and swiping right pulls up a pin button to toggle a pin for the note or just pin the note outright.

**Comment by redsolver** [comment]
Added in https://github.com/redsolver/notable-mobile/commit/e4e2494943f82c0114f1e7ee3dd46cd981e9e7c4
