### ISSUE TITLE
[Enhancement] Accent colour

### ISSUE THREAD

**Issue by spiral6** [redsolver/notable-mobile#15]
Currently the app is looking very good, but one nice addition would be something similar to Textra where the accent colour of the app could be changed (either with a hex code or preset pallette). The accent colour would affect the title bar, left nav bar text/icon highlight and floating action bar.

**Comment by redsolver** [comment]
Closed with https://github.com/redsolver/notable-mobile/commit/dc04d2ed2ec8b6973cf465bc25f23f2021b3149f
