### ISSUE TITLE
Notes read from notes subdirectory

### ISSUE THREAD

**Issue by spiral6** [redsolver/notable-mobile#25]
The desktop app of Notable does not care which folder a note is in, so long as it is under the `notes` directory. Regardless if it is in the root `notes` directory or a subdirectory or anything under that, it will always read the note, provided that the note has the correct markdown extension (such as .md, .markdown, etc).

**Comment by spiral6** [comment]
That being said, it is particularly useful for some people to organize their notes a lot easier.

**Comment by redsolver** [comment]
Should the app show a "virtual tag" for the file path, if it isn't in the root directory?

**Comment by NomarCub** [comment]
I think he means that if you put your notes in a subfolder under the data directory Notable mobile doesn't scan them at all, but the original Notable on desktop does. This should be fixed.

I'm all for virtual folder tags, but that's a separate [issue](github.com/notable/notable/issues/54) that people can't even agree if it should be part of Notable desktop.
